### ISSUE TITLE
SendTransactionWithReceipt: sending transaction failed due to timeout

### ISSUE THREAD

**Issue by joshua-mir** [paritytech/parity-bridge#217] opened 2019-05-29 10:29 UTC
```
DeployMain: deployment transaction failed

Caused by:
    SendTransactionWithReceipt: sending transaction failed

Caused by:
    Request timed out
```

Possibly related to #213

**Comment by tomusdrw** [comment] 2019-10-29 15:07
Assuming duplicate of #213

**Closed by tomusdrw** 2019-10-29 15:07 UTC
Labels: F3-annoyance, M4-core
