### ISSUE TITLE
Add ERC20 support

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-bridge#85] opened 2018-01-16 16:16 UTC
make `ForeignBridge` implement ERC20 so tokens on `foreign` can be used in a standardized way

**Comment by snd** [comment] 2018-01-17 09:20
@bjornwgnr what's the context and priority of this?

**Comment by snd** [comment] 2018-01-17 09:25
this is a fairly straightforward change (max 2 days including 100% test coverage)

**Comment by akolotov** [comment] 2018-01-18 01:17
You could consider another approach: 

- bridge.sol: https://gitlab.com/alex.kolotov/parity-bridge-research/raw/master/erc20/bridge/contracts/bridge.sol
- BridgeableToken.sol: https://gitlab.com/alex.kolotov/parity-bridge-research/raw/master/erc20/bridge/token/BridgeableToken.sol

The action flow could be:
1. The bridge deploys the home and foreign contracts.
2. An end user deploys BridgeableToken contract, mint bunch of tokens and transfer them to the foreign contract.
3. A user in the home network does deposit and check tokens in the token contract on the foreign side.
4. The user invokes `approveAndCall` in the token contract with the amount of tokens to transfer back to the home side and address of the foreign token contract. It leads to invocaction of `receiveApproval` in the foreign contract and `Withdraw` envent emission.
5. The bridge exchanges the tokens to the coins on the home side.

This approach looks more common since the token contract does not depend on the bridge contracts and completely follows ERC20/223 recommendations to manage tokens. 

I cannot test this in full manner due to https://github.com/paritytech/parity-bridge/issues/87. So as soon as the issue is closed I could confirm coins to tokens exchange by using the parity-bridge software.

**Comment by snd** [comment] 2018-01-18 09:21
@akolotov 

> This approach looks more general since the token contract does not depend on the bridge contracts and completely follows ERC20/223 recommendations to manage tokens.

could you describe in more detail the **pros** of the approach you laid out over simply making `ForeignBridge` implement `ERC20`? the current use case we're aiming to enable with this issue is "make tokens on ForeignBridge usable according to ERC20". is this use case enabled by the proposed approach? what other use cases are enabled by the approach?

**Comment by akolotov** [comment] 2018-01-18 09:37
OK. If ERC20 is built in the foreign bridge contract it means that anyone who needs a bit extended functionality of the the token (mintable, burnable, time locked etc) should modify the bridge contract. So, the token functionality will be too tied with the bridge functionality. And this is really is not good practice if the bridge considered as independent part of the solution. 

By separating the functionality the same bridge distribution could serve different kinds of ERC20 tokens and this should promote side-chains usage: coins on the side-chain could be used for side-chains operations and could be transferred as tokens to the main net where they can be sold on exchanges.

**Comment by snd** [comment] 2018-01-18 10:01
interesting.

am i understanding this correctly?:
you want users to be able to deposit ether into the bridge on `home` and then have it deposited into their own token contract on `foreign` that they have full control over, instead of having it deposited into one singular limited token contract that is part of the bridge.

**Comment by akolotov** [comment] 2018-01-18 10:13
right. imagine that the home side is a sidechain and the foreign side is the official Ethereum network. It would increase opportunities for dapps.

**Comment by snd** [comment] 2018-01-18 10:52
@akolotov is this something you need for what you're working on?

> imagine that the home side is a sidechain and the foreign side is the official Ethereum network

i like the implied idea of representing ether on a sidechain as a token on home chain.
this would be a different kind of bridge however.
not saying parity-bridge won't eventually support things like this.
currently however `home` can be any chain but `foreign` must be a PoA chain so `foreign` can't be the official ethereum network! see https://github.com/paritytech/parity-bridge#current-functionality.

**Comment by akolotov** [comment] 2018-01-18 10:58
@snd I do not see any limitation in the code why the foreign side cannot be the official ethereum network?

**Comment by snd** [comment] 2018-01-18 11:23
currently we assume that transactions by the bridge authorities are free on `foreign`.
this is the case when `foreign` is a PoA chain and the bridge authorities are also the authorities of `foreign`.

bridge authorities pay all gas costs for relays.
only on the `home` side do they get back the relay costs https://github.com/paritytech/parity-bridge#recipient-pays-relay-cost-to-relaying-authority.
on `foreign`, where most transactions required for relays happen, authorities currently don’t get repaid for transaction costs. it was an intentional complexity introducing performance optimization to collect signatures on foreign in order to be able to relay withdraw in a single transaction.

this is all fine as long as those transactions on `foreign` are free.
if they were not free authorities would require an ether balance on `foreign` that would need regular topping up.
this would not be much of a problem on a testnet where they could use a faucet to top up.
but if `foreign` were ethereum foundation then running a bridge authority currently would regularly cost ether and there would be attacks that spend authorities ether.

we could modify the bridge to remove those problems and close attack vectors arising from them.
that would introduce additional complexity.
since all our current use cases work with `foreign` being PoA we like to keep it simple and keep that assumption for the time being.

the bridge is early work in progress and as it bridge evolves that might change.

**Comment by akolotov** [comment] 2018-01-18 12:08
Thanks, it is my understanding also. So, there is no technical limitations just financial ones. This is solvable.

You said that 
> in order to be able to relay withdraw in a single expensive transaction on `home`.

But my current understanding is different. Any bridge instance will receive `CollectedSignatures` and since there is no consensus between two instances of bridges, every bridge will invoke `withdraw` on the `home` contract side. Only the first mined transaction will be applied in full manner and other requests will be handled as duplicated by the code of the method `withdraw`. So, every bridge will pay at least for the transaction and its data (full set of signatures and message bytes) and only one bridge will be compensated with the relay costs. Assuming that we have at least three instances of bridges we need to configure the relay costs as the consumption of one full transaction and two transactions terminated due to duplication.

**Comment by snd** [comment] 2018-01-18 12:27
> So, every bridge will pay at least for the transaction and its data (full set of signatures and message bytes) and only one bridge will be compensated with the relay costs. Assuming that we have at least three instances of bridges we need to configure the relay costs as the consumption of one full transaction and two transactions terminated due to duplication.

no. only one non-faulty bridge calls `withdraw` per relay. the one that submitted the signature last. it is chosen as the authority responsible for the relay. anyone (even non authorities) can call `withdraw` with a correct signed message. `HomeBridge` trusts the signatures of enough authorities and doesn't have to trust the sender of `withdraw`. this enables everyone to unstuck relays in case the chosen authority fails to relay. we'll implement a more robust retrying functionality in the future.

see
https://github.com/paritytech/parity-bridge/blob/1cef1596a48edbf360833e23420e4d76020d8f75/bridge/src/bridge/withdraw_relay.rs#L39

also see
https://github.com/paritytech/parity-bridge/#withdraw-balance-on-foreignbridge-and-get-it-as-ether-on-home-chain

> So, there is no technical limitations just financial ones. This is solvable.

solvable, yes. it's more about limiting the scope of the project though. every feature and generalization adds complexity. we want to keep the bridge simple while solving a couple of important use cases. that might require us to decide against implementing certain features or making the bridge work in specific circumstances.

**Comment by akolotov** [comment] 2018-01-18 12:44
> only one non-faulty bridge calls withdraw per relay. the one that submitted the signature last. it is chosen as the authority responsible for the relay
Thanks! I missed this functionality during my acquaintance with the code. Nice solution!
And you comment regarding failed relay operation is true. Currently just restart of the bridge could solve issues with stuck operations.

> every feature and generalization adds complexity. we want to keep the bridge simple while solving a couple of important use cases
I meant that it is solvable by financial part of a project. It could part of fees users pay for token usage or could be planned as part of coins distribution.

**Comment by snd** [comment] 2018-01-18 13:38
@akolotov could you open a separate issue for your proposed approach (with a link to this issue)? then we can continue discussion there. keeps things separate and others looking for something similar to what you're suggesting have an easier way of finding it. i think we'll finish making `ForeignBridge` implement ERC20 soon as it's easy and gives more structure to `ForeignBridge`. what you're describing is definitely worth further thought and discussion but will likely happen at a later date

**Comment by snd** [comment] 2018-01-29 11:06
resolved in https://github.com/paritytech/parity-bridge/pull/86

@akolotov see comment above

**Closed by snd** 2018-01-29 11:06 UTC
Labels: F8-enhancement, P5-sometimesoon
