### ISSUE TITLE
Ubuntu 16.04 compilation issue

### ISSUE THREAD

**Issue by dev3467** [paritytech/parity-bridge#210] opened 2019-01-30 22:00 UTC
Hi,

I have issue with compilation on ubuntu. I used solc 0.5.2 and cargo 1.3.2:

Error: failed to run custom build command for `bridge-contracts v0.5.0 (/opt/parity/parity-bridge/contracts)`
process didn't exit successfully: `/opt/parity/parity-bridge/target/release/build/bridge-contracts-5efb5b897267822a/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../arbitrary/contracts/bridge.sol
cargo:rustc-env=GIT_HASH=bb9046874113a59af20d78d46adadd32fbcd3325

cargo:rustc-env=SOLC_VERSION=Version: 0.5.2-develop.2018.12.18+commit.eed46f00.Linux.g++

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(ExitStatusNotSuccess("solc", ExitStatus(ExitStatus(256))), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Thanks for help.

**Comment by joshua-mir** [comment] 2019-02-28 16:26
duplicate of https://github.com/paritytech/parity-bridge/issues/212
can you try the solution outlined there?

**Comment by joshua-mir** [comment] 2019-02-28 16:29
specifically, you want to `git submodule init` and then `git submodule update`

**Closed** 2019-10-29 14:51 UTC
Labels: M0-build, Z0-duplicate, Z0-question
